plugins {
    id 'java-library'
}

tasks.withType(JavaCompile) {
    options.encoding 'UTF-8'
    options.compilerArgs.add("-parameters")
}

tasks.withType(Test) {
    useJUnitPlatform()
}

dependencies {
	api project(':uaa-authorization')
	api project(':uaa-authentication-spring-boot-autoconfigure')

	api libs.springBootAutoconfigure
	annotationProcessor libs.springBootConfigProcessor
	api libs.springBootStarterValidation
	api libs.springWeb
	api libs.springSecurityWeb
	implementation libs.servletApi

	testImplementation libs.junitJupter
	testImplementation libs.junitPlatformLauncher
	testImplementation libs.mockitoJunit
	testImplementation libs.springTest
}

description = 'UAA:: Authorization WEB:: Spring Boot AutoConfiguration'


