plugins {
    id 'org.springframework.boot' version '3.5.5'
	id 'base'
	id 'jacoco'
    id 'io.freefair.aggregate-javadoc' version '6.6.3'
    id 'org.asciidoctor.jvm.convert' version '4.0.2'
	id 'java-platform'
	id 'version-catalog'
    id 'com.github.node-gradle.node' version '7.1.0'
}

// Documentation Configuration
tasks.named('aggregateJavadoc') {
	failOnError = false
	destinationDir = new File("${project.getBuildDir()}/docs/assets/javadoc")
	excludes = ['**/com/mgmtp/a12/uaa/example/**']
}

tasks.register('aggregateTypedoc', Copy) {
	group = 'documentation'
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	from project.project(':uaa-authentication-client').tasks.matching { Task task -> task.name == 'typedoc' && task.enabled }
	into "${project.getBuildDir()}/docs/assets/typedoc"
}

