plugins {
    id 'java-library'
}

tasks.withType(JavaCompile) {
    options.encoding 'UTF-8'
    options.compilerArgs.add("-parameters")
}

tasks.withType(Test) {
    useJUnitPlatform()
}

dependencies {
    api project(':uaa-authorization')
    api libs.springWebMvc

    testImplementation libs.bundles.springTest
}

description = 'UAA:: Authorization Endpoint Introspector'
