////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License – EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
Below is a set of examples for each authentication types:

===== LOCAL
[source,java]
----
public class ProjectLocalRestClientFactory {
	private UAARestClientFactory factory = createFactory();

	public static restClientFactory() {
		return factory;
	}

	private UAARestClientFactory createFactory() {
				UAARestClientProperties uaaRestConfig = new UAARestClientProperties();
		uaaRestConfig.setSelfconfiguration(new UrlProperty("{http}://{uaa-server-host}/{uaa-context-path}/uaa-authentication/selfconfigure"));
		uaaRestConfig.setAuthenticationType(AuthenticationType.LOCAL);
		UAARestClientAuthenticationProperties authConfig = new UAARestClientAuthenticationProperties();
		authConfig.setUsername(username);
		authConfig.setPassword(password);
		uaaRestConfig.setAuthenticationConfiguration(authConfig);
		return UAARestClientFactoryBuilder.withConfiguration(uaaRestConfig).build();
	}

}

public class ProjectUsage {
	private AuthenticationRestClient authClient =  ProjectLocalRestClientFactory.restClientFactory().getAuthenticationRestClient();

	public void aMethod() {
		CurrentUser currentUser = authClient.currentUser();
	}
}

----

===== ACTIVE_DIRECTORY_LDAP
[source,java]
----

public class ProjectLdapRestClientFactory {
	private UAARestClientFactory factory = createFactory();

	public static restClientFactory() {
		return factory;
	}

	private UAARestClientFactory createFactory() {
		UAARestClientProperties uaaRestConfig = new UAARestClientProperties();
		uaaRestConfig.setSelfconfiguration(new UrlProperty("{http}://{uaa-server-host}/{uaa-context-path}/uaa-authentication/selfconfigure"));
		uaaRestConfig.setAuthenticationType(AuthenticationType.ACTIVE_DIRECTORY_LDAP);
		UAARestClientAuthenticationProperties authConfig = new UAARestClientAuthenticationProperties();
		authConfig.setUsername("{username}");
		authConfig.setPassword("{password}");
		uaaRestConfig.setAuthenticationConfiguration(authConfig);
		return UAARestClientFactoryBuilder.withConfiguration(uaaRestConfig).build();
	}

}

public class ProjectUsage {
	private AuthenticationRestClient authClient =  ProjectLdapRestClientFactory.restClientFactory().getAuthenticationRestClient();

	public void aMethod() {
		CurrentUser currentUser = authClient.currentUser();
	}
}

----


===== SAML
[source,java]
----
public class ProjectSamlRestClientFactory {
	private UAARestClientFactory factory = createFactory();

	public static restClientFactory() {
		return factory;
	}

	private UAARestClientFactory createFactory() {
		UAARestClientProperties uaaRestConfig = new UAARestClientProperties();
		uaaRestConfig.setSelfconfiguration(new UrlProperty("{http}://{uaa-server-host}/{uaa-context-path}/uaa-authentication/selfconfigure"));
		uaaRestConfig.setAuthenticationType(AuthenticationType.SAML);
		UAARestClientAuthenticationProperties authConfig = new UAARestClientAuthenticationProperties();
		authConfig.setUsername("{username}");
		authConfig.setPassword("{password}");
		uaaRestConfig.setAuthenticationConfiguration(authConfig);
		return UAARestClientFactoryBuilder.withConfiguration(uaaRestConfig).build();
	}

}

public class ProjectUsage {
	private AuthenticationRestClient authClient =  ProjectSamlRestClientFactory.restClientFactory().getAuthenticationRestClient();

	public void aMethod() {
		CurrentUser currentUser = authClient.currentUser();
	}
}

----

===== OAUTH2 (PUBLIC)
[source,java]
----

public class ProjectOauth2RestClientFactory {
	private UAARestClientFactory factory = createFactory();

	public static restClientFactory() {
		return factory;
	}

	private UAARestClientFactory createFactory() {
		UAARestClientProperties uaaRestConfig = new UAARestClientProperties();
		uaaRestConfig.setSelfconfiguration(new UrlProperty("{http}://{uaa-server-host}/{uaa-context-path}/uaa-authentication/selfconfigure"));
		uaaRestConfig.setAuthenticationType(AuthenticationType.OAUTH2);
		UAARestClientAuthenticationProperties authConfig = new UAARestClientAuthenticationProperties();
		authConfig.setUsername("{username}");
		authConfig.setPassword("{password}");
		Oauth2Properties oauth2Properties = new Oauth2Properties();
		oauth2Properties.setClientType(ClientType.PUBLIC);
		authConfig.setOauth2(oauth2Properties);
		uaaRestConfig.setAuthenticationConfiguration(authConfig);
		return UAARestClientFactoryBuilder
				.withConfiguration(uaaRestConfig)
				.build();
	}

}

public class ProjectUsage {
	private AuthenticationRestClient authClient =  ProjectOauth2RestClientFactory.restClientFactory().getAuthenticationRestClient();

	public void aMethod() {
		CurrentUser currentUser = authClient.currentUser();
	}
}

----

===== OAUTH2 (CONFIDENTIAL)
[source,java]
----
public class ProjectOauth2RestClientFactory {
	private UAARestClientFactory factory = createFactory();

	public static restClientFactory() {
		return factory;
	}

	private UAARestClientFactory createFactory() {
		UAARestClientProperties uaaRestConfig = new UAARestClientProperties();
		uaaRestConfig.setSelfconfiguration(new UrlProperty("{http}://{uaa-server-host}/{uaa-context-path}/uaa-authentication/selfconfigure"));
		uaaRestConfig.setAuthenticationType(AuthenticationType.OAUTH2);
		UAARestClientAuthenticationProperties authConfig = new UAARestClientAuthenticationProperties();
		authConfig.setUsername("{username}");
		authConfig.setPassword("{password}");
		Oauth2Properties oauth2Properties = new Oauth2Properties();
		Oauth2Properties.ConfidentialClientProperties confidentialClientProperties = new Oauth2Properties.ConfidentialClientProperties();
		confidentialClientProperties.setClientSecret("{client-secret}");
		oauth2Properties.setConfidentialClient(confidentialClientProperties);
		authConfig.setOauth2(oauth2Properties);
		uaaRestConfig.setAuthenticationConfiguration(authConfig);
		return UAARestClientFactoryBuilder
				.withConfiguration(uaaRestConfig)
				.build();
	}

}

public class ProjectUsage {
	private AuthenticationRestClient authClient =  ProjectOauth2RestClientFactory.restClientFactory().getAuthenticationRestClient();

	public void aMethod() {
		CurrentUser currentUser = authClient.currentUser();
	}
}

----

===== CERTIFICATE
[source,java]
----
public class ProjectCertificateRestClientFactory {
	private UAARestClientFactory factory = createFactory();

	public static restClientFactory() {
		return factory;
	}

	private UAARestClientFactory createFactory() {
		CertificateProperties certificateProperties = new CertificateProperties();
		certificateProperties.setKeyStore("classpath:${KeyStorePath}");
		certificateProperties.setkeyStorePassword("${KeyStorePassword}");
		certificateProperties.settrustStore("classpath:${TrustStorePath}");
		certificateProperties.settrustStorePassword("${TrustStorePassword}");
		UAARestClientAuthenticationProperties authConfig = new UAARestClientAuthenticationProperties();
		authConfig.setCertificate(certificateProperties);
		UAARestClientProperties uaaRestConfig = new UAARestClientProperties();
		uaaRestConfig.setSelfconfiguration(new UrlProperty("{http}://{uaa-server-host}/{uaa-context-path}/uaa-authentication/selfconfigure"));
		uaaRestConfig.setAuthenticationType(AuthenticationType.CERTIFICATE);
		uaaRestConfig.setAuthenticationConfiguration(authConfig);
		return UAARestClientFactoryBuilder
				.withConfiguration(uaaRestConfig)
				.build();
	}

}

public class ProjectUsage {
	private AuthenticationRestClient authClient =  ProjectCertificateRestClientFactory.restClientFactory().getAuthenticationRestClient();

	public void aMethod() {
		CurrentUser currentUser = authClient.currentUser();
	}
}

----

===== API_KEY
[source,java]
----
public class ProjectAPIKeyRestClientFactory {
	private UAARestClientFactory factory = createFactory();

	public static restClientFactory() {
		return factory;
	}

	private UAARestClientFactory createFactory() {
		UAARestClientProperties uaaRestConfig = new UAARestClientProperties();
		uaaRestConfig.setSelfconfiguration(new UrlProperty("{http}://{uaa-server-host}/{uaa-context-path}/uaa-authentication/selfconfigure"));
		uaaRestConfig.setAuthenticationType(AuthenticationType.API_KEY);
		uaaRestConfig.setAPIKeyResource("classpath:/{path}/{apikey-name}.crt");
		return UAARestClientFactoryBuilder
				.withConfiguration(uaaRestConfig)
				.build();
	}

}

public class ProjectUsage {
	private AuthenticationRestClient authClient =  ProjectAPIKeyRestClientFactory.restClientFactory().getAuthenticationRestClient();

	public void aMethod() {
		CurrentUser currentUser = authClient.currentUser();
	}
}

----
