mgmtp.a12.uaa.authentication.jwt.secret=MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
mgmtp.a12.uaa.authentication.jwt.expiration-seconds=100
mgmtp.a12.uaa.authentication.jwt.token-renew-threshold-in-seconds=50
mgmtp.a12.uaa.authentication.jwt.store-user-in-token.enabled=true
