mgmtp.a12.uaa.authentication.principal.additional-properties=nationality,email
mgmtp.a12.uaa.authentication.principal.access-rights-resource=classpath:/access_rights.yaml
mgmtp.a12.uaa.authentication.principal.local-config.user-resources=classpath:users/*.yaml
