# Actuator
management.endpoints.web.exposure.include=*
management.health.ldap.enabled=false
management.endpoint.shutdown.access=read_only

# Client Self-Configuration
mgmtp.a12.uaa.authentication.client-selfconfiguration.authorizationDataStore=classpath:storage/auth.txt
mgmtp.a12.uaa.authentication.client-selfconfiguration.cache.enabled=true
mgmtp.a12.uaa.authentication.client-selfconfiguration.cache.mapping[0].cache-path-pattern=/uaa-authentication/currentUser
mgmtp.a12.uaa.authentication.client-selfconfiguration.cache.mapping[0].region-pattern=/uaa-authentication/*

mgmtp.a12.uaa.authentication.unsecured.urls=/actuator/health,/federation/loadAllCompanies
mgmtp.a12.uaa.authorization.authorization-definition=classpath:/authorizationDefinition.json
mgmtp.a12.uaa.authentication.cors.allowed-origins=${config.client.url:http://localhost:3000},${config.idp.url:http://localhost:9090},null
mgmtp.a12.uaa.authentication.cors.allow-credentials=true

mgmtp.a12.uaa.authentication.cookie.http-only.enabled=true
mgmtp.a12.uaa.authentication.cached-token-storage.enabled=true

mgmtp.a12.uaa.authorization.web.uri-secured-contexts=${management.endpoints.web.base-path:/actuator}/**::RelativePath,/uri-based-authorization/forbidden::UriBasedForbiddenScope,/uri-based-authorization/ok::uri_based_ok_scope
mgmtp.a12.uaa.authorization.web.introspection.whitelist-endpoints=/error, /image, /uaa-authentication/currentUser
