mgmtp.a12.uaa.authentication.types=CERTIFICATE
server.ssl.key-store=classpath:certificate/server.p12
server.ssl.key-store-password=CustomExampleServerAppKeyStorePassword
server.ssl.key-store-type=PKCS12
server.ssl.client-auth=WANT
server.ssl.trust-store=classpath:certificate/truststore.p12
server.ssl.trust-store-password=CustomExampleAppTrustStorePassword
server.ssl.trust-store-type=PKCS12

mgmtp.a12.uaa.authentication.certificate-white-list-access-url-patterns=/**
