mgmtp.a12.uaa.authentication.types=SAML
mgmtp.a12.uaa.authentication.jwt.compress-user.enabled=true
mgmtp.a12.uaa.authentication.saml.login.url=${config.server.url:http://localhost:8080}/saml2/authenticate/uaa
mgmtp.a12.uaa.authentication.logout.redirect.url-pattern=.*

mgmtp.a12.uaa.authentication.login.redirect.failure.url=${config.server.url:http://localhost:8080}/login
mgmtp.a12.uaa.authentication.login.redirect.url-pattern=.*

mgmtp.a12.uaa.authentication.client-selfconfiguration.saml.login-relative.url=saml2/authenticate/uaa?uaa_success=${config.server.saml.redirect:http://localhost:3000}&uaa_failure=${config.server.saml.redirect:http://localhost:3000}/silent_renew
mgmtp.a12.uaa.authentication.client-selfconfiguration.saml.logout-relative.url=user/logout?uaa_success=${config.server.saml.redirect:http://localhost:3000}
mgmtp.a12.uaa.authentication.client-selfconfiguration.saml.logout-method=POST

server.servlet.session.cookie.http-only=true
mgmtp.a12.uaa.authentication.saml.idp-logout.enabled=true
mgmtp.a12.uaa.authentication.saml.force-auth.enabled=true

mgmtp.a12.uaa.authentication.saml.authorization-code-expiration-seconds=30

# Registrations
spring.security.saml2.relyingparty.registration.uaa.assertingparty.metadata-uri=${config.idp.url:http://localhost:9090}/realms/UAARealm/protocol/saml/descriptor
spring.security.saml2.relyingparty.registration.uaa.entity-id=urn:com:mgm:UAA
spring.security.saml2.relyingparty.registration.uaa.signing.credentials[0].private-key-location=classpath:encryption/sign_private.key
spring.security.saml2.relyingparty.registration.uaa.signing.credentials[0].certificate-location=classpath:encryption/sign_certificate.crt
spring.security.saml2.relyingparty.registration.uaa.decryption.credentials[0].private-key-location=classpath:encryption/enc_private.key
spring.security.saml2.relyingparty.registration.uaa.decryption.credentials[0].certificate-location=classpath:encryption/enc_certificate.crt

spring.security.saml2.relyingparty.registration.uaa.singlelogout.response-url={baseUrl}/logout/saml2/slo
spring.security.saml2.relyingparty.registration.uaa.singlelogout.binding=post
spring.security.saml2.relyingparty.registration.uaa.assertingparty.singlesignon.binding=post

#this is just for regular SML
mgmtp.a12.uaa.authentication.saml.signing-algorithm.url==http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1
