logging.level.root=INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.com.mgmtp.a12.uaa.authorization.security=TRACE
logging.level.com.mgmtp.a12.uaa.authorization.property=TRACE
logging.level.com.mgmtp.a12.uaa.example.backend.BackendTask=INFO
logging.level.com.mgmtp.a12.uaa.authentication.backend.internal.AuthenticatedAspect=WARN
logging.level.com.mgmtp.a12.uaa.authentication.saml.internal.SamlAuthenticationRequestCleaner=WARN
logging.level.com.mgmtp.a12.uaa.authentication.saml.internal.SamlJwtTokenCleaner=WARN
logging.level.com.mgmtp.a12.uaa.authentication.backend=WARN
logging.level.org.springframework.web.cors=TRACE
logging.level.org.springframework.cache=TRACE
logging.level.com.mgmtp.a12.uaa.authentication.saml.internal.SamlAuthorizationCodeCleaner=WARN
logging.level.com.mgmtp.a12.uaa.authorization.security.spel=DEBUG
