mgmtp.a12.uaa.authentication.types=ACTIVE_DIRECTORY_LDAP
mgmtp.a12.uaa.authentication.ldap.url=${config.ldap.url:ldap://localhost:389}
mgmtp.a12.uaa.authentication.ldap.domain=sambaad.local
mgmtp.a12.uaa.authentication.ldap.root-dn=DC=sambaad,DC=local
