mgmtp.a12.uaa.authentication.types=OAUTH2

# Logout - Oauth2 Client
mgmtp.a12.uaa.authentication.oauth2.idp-logout.enabled=true
mgmtp.a12.uaa.authentication.oauth2.post-logout.url=${config.server.url:http://localhost:8080}

# Confidential Client
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.confidential-client.idp-base.url=${config.idp.url:http://localhost:9090}
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.confidential-client.client-id=uaa-auth-client
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.confidential-client.realm-name=UAARealm

# Public Client
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.public-client.idp-base.url=${config.idp.url:http://localhost:9090}
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.public-client.client-id=uaa-spa-client
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.public-client.realm-name=UAARealm
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.public-client.currentUserUrl=http://localhost:8080/uaa-authentication/currentUser
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.public-client.enable-refresh-token-grant=false
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.public-client.sso-configuration.username-xpath=//input[@name='username']
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.public-client.sso-configuration.password-xpath=//input[@name='password']
mgmtp.a12.uaa.authentication.client-selfconfiguration.oidc.public-client.sso-configuration.login-button-xpath=//button[@name='login']
