mgmtp.a12.uaa.authentication.types=LOCAL
# Due to the project is having dependency on principal-extension module so this property is required, the definition here is only a bypass.
mgmtp.a12.uaa.authentication.principal.local-config.user-resources=classpath:users/*.yaml
