spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=http://localhost:9090/realms/UAARealm/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id=uaa-auth-client
spring.security.oauth2.resourceserver.opaquetoken.client-secret=abfab5c9-ec40-4c1d-893d-e731f5552950
