mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[0].jwt.issuer-uri=http://localhost:9090/realms/UAARealm
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[0].jwt.jwk-set-uri=http://localhost:9090/realms/UAARealm/protocol/openid-connect/certs
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[0].jwt.jws-algorithms=RS256
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[0].jwt.audiences=uaa-spa-client,account
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[0].jwt.public-key-location=classpath:certificate/UAARealmRS256PublicKey.pub
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[1].opaquetoken.introspection-uri=http://localhost:9090/realms/UAARealm/protocol/openid-connect/token/introspect
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[1].opaquetoken.client-id=uaa-auth-client
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[1].opaquetoken.client-secret=abfab5c9-ec40-4c1d-893d-e731f5552950

mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[2].jwt.issuer-uri=http://localhost:9090/realms/UAARealmII
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[2].jwt.jwk-set-uri=http://localhost:9090/realms/UAARealmII/protocol/openid-connect/certs
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[2].jwt.jws-algorithms=RS256
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[2].jwt.public-key-location=classpath:certificate/UAARealmRS256PublicKey.pub
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[3].opaquetoken.introspection-uri=http://localhost:9090/realms/UAARealmII/protocol/openid-connect/token/introspect
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[3].opaquetoken.client-id=uaa-auth-client
mgmtp.a12.uaa.authentication.oauth2.resourceserver.tenants[3].opaquetoken.client-secret=abfab5c9-ec40-4c1d-893d-e731f5552950
