spring.profiles.include=security,\
  embedded_db,\
  logging

spring.profiles.group.uaa_all_types=jwt,principal,anonymous,local,uaa_apikey_basic,ldap,oauth2,oauth2_jwt,saml,all_types
spring.profiles.group.uaa_all_types_basic=jwt,anonymous,local,uaa_apikey_basic,ldap,oauth2,oauth2_jwt,saml,all_types

spring.profiles.group.uaa_anonymous=anonymous,principal

spring.profiles.group.uaa_local=jwt,local,principal
spring.profiles.group.uaa_local_basic=jwt,local

spring.profiles.group.uaa_ldap=jwt,ldap,principal
spring.profiles.group.uaa_ldap_basic=jwt,ldap

spring.profiles.group.uaa_apikey=uaa_apikey_basic,principal

spring.profiles.group.uaa_certificate=uaa_certificate_basic,principal

spring.profiles.group.uaa_access_token=jwt,access_token

spring.profiles.group.uaa_saml=jwt,saml,principal
spring.profiles.group.uaa_saml_basic=jwt,saml

spring.profiles.group.uaa_oauth2=oauth2,oauth2_jwt,principal
spring.profiles.group.uaa_oauth2_basic=oauth2,oauth2_jwt,principal
spring.profiles.group.uaa_oauth2_opaque=oauth2,oauth2_opaque,principal
spring.profiles.group.uaa_oauth2_opaque_basic=oauth2,oauth2_opaque
spring.profiles.group.uaa_oauth2_multi_tenants=oauth2,oauth2_multi_tenants,principal

server.port=8080
# Cache
spring.cache.type=jcache
spring.cache.jcache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.cache.cache-names=tokenCache,authorizationCodeCache,samlLogoutRequestCache,roleMapping,codeChallengeCache,codeCache,tokenHintCache,samlAuthenticationRequestCache,samlJwtTokenCache

# Set true to use custom UserDetailsService
mgmtp.a12.uaa.example.use-user-details.enabled=false
