mgmtp.a12.uaa.authentication.types=API_KEY
mgmtp.a12.uaa.authentication.api-key-authority-resources=classpath:/apikey/rootCA.crt
mgmtp.a12.uaa.authentication.api-key-white-list-access-url-patterns=/**
