////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License – EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////

=== Development environment issues
[qanda]
Silent renew not work on Chrome from version 85 and above?:: (It always returns login_required even the request has the correct token)
* By SameSite cookie attribute definition, the origin's registrable domain is an exact match for the request's client's "site for cookies". And from Chrome version 85 to the latest, the Samesite cookie attribute will be enabled by default with the value Samesite=None. It makes the silent renew doesn't work if you use a different domain. But it still works for the subdomain. The valid domain, for example, could be client: client.application.com and Keycloak server keycloak.application.com.
* In case, you want to use a local client and remote IDP server. You can by-pass by mapping localhost with an address that has the same domain name.
