spring.application.name=test2
mgmtp.a12.uaa.authentication.client.rest.uaa-base.url=https://localhost:8080
mgmtp.a12.uaa.authentication.client.rest.authentication-configuration.certificate.key-store=classpath:certificate/client.p12
mgmtp.a12.uaa.authentication.client.rest.authentication-configuration.certificate.key-store-password=CustomExampleClientAppKeyStorePassword
mgmtp.a12.uaa.authentication.client.rest.authentication-configuration.certificate.trust-store=classpath:certificate/truststore.p12
mgmtp.a12.uaa.authentication.client.rest.authentication-configuration.certificate.trust-store-password=CustomExampleAppTrustStorePassword

# for API_KEY
#mgmtp.a12.uaa.authentication.client.rest.api-key-resource=classpath:/apikey/client.crt

server.port=8081
mgmtp.a12.uaa.authentication.client.rest.authentication-type=CERTIFICATE

#mgmtp.a12.uaa.authentication.client.rest.authentication-configuration.login-relative.url=/user/local/login
spring.cache.type=JCACHE
#spring.cache.jcache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.cache.cache-names=currentUser
mgmtp.a12.uaa.authentication.client.rest.cache.enabled=true
#mgmtp.a12.uaa.authentication.client.rest.cache.mapping[0].cache-path-pattern=/uaa-authentication/currentUser
#mgmtp.a12.uaa.authentication.client.rest.cache.mapping[0].region-pattern=/uaa-authentication/*
#mgmtp.a12.uaa.authentication.client.rest.cache.mapping[0].static-name=xyz

logging.level.com.mgmtp.a12.connector.rest=DEBUG
#logging.level.com.mgmtp.a12.uaa.client.rest=DEBUG
logging.level.com.mgmtp.a12.uaa.client.rest.cache=DEBUG
logging.level.com.mgmtp.a12.uaa.client.rest.auth.internal=DEBUG
