////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License – EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
====== OpenIDConnect with Proof Key for Code Exchange (PKCE)
PKCE (pronounced "pixy") is a security extension to OAuth 2.0 for public clients on mobile devices and browser,
designed to prevent the interception of the authorisation code by a malicious application that has sneaked into the same device

UAA with OIDC-PKCE: uaa-authentication-client provides a set of configurations to allow
a Single Page Application "speaks" with any IDP Servers in Public Type with PKCE enable based on OpenIDConnect protocol.

====== How to setup silent renew. It's completely dependent on project to set this up. Below is example
* Serve additional html file eg: silent_renew.html with content:
[source, html]
    <!DOCTYPE html>
    <html><head>
        <script type="text/javascript" src="[your path to silent_renew.js]"></script>
        </body>
    </head>
    <body>
    <div></div>
    </body>
    </html>

* Configure your webpack to serve it as separate resource:
[source,javascript]
new HtmlWebpackPlugin({
    minify: true,
    filename: "silent_renew.html",
    template: [directory_to_your_silent_renew.html]
}),
entry: {
    silent_renew: [your path to silent_renew.js]
}

[NOTE]
====
`silent_renew.js` can be found from "node_modules", "@com.mgmtp.a12", "uaa-authentication-client", "resources", "silent_renew.js"
====

[WARNING]
====
Following Content Security Policy please do not use the default `silent_renew.html` provided by UAA for serving the renewal token. (We will remove it)
====