////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License – EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
== Breaking and Non-breaking Interpretation

=== Definition of Version
The UAA product defines a single version. All artifacts (Java and Javascript) that belong to the UAA product share the same version.

The following definition of breaking changes only applies to specified functionality of libraries that we provide.

Furthermore, any change is only guaranteed to be non-breaking if all artifacts of a product are used in exactly the same version.

=== Definition of Documented Functionality

* All functions which are NOT mentioned in Documentation are considered internal.

* All EXPERIMENTAL functions will not followed breaking changes management.

* Modules (Javascript) in the "experimental" folder are also not considered regarding breaking changes.

* All blocker tickets regarding Security Fixes with evaluation from SP are not follow breaking changes.
[#table-cbq-shell-commands,cols="1,2,4",options="header"]
|===
^|Breaking ^|Non breaking

2+^| Public API
a|
[#set-var-types]
* Incompatible change of API signatures - cause compile errors.
* Change in functionality.
* Change Rest Endpoints.

a|
[#set-var-types]
* Compatible change of API signatures
* Change of experimental functionality
* Change of unspecified method signatures
* Change of experimental method signatures
* Change of internal method signatures

* Addition of optional new functionality
* Correction of functionality that does not fulfil the specification - fixing bugs
* Change of unspecified functionality

2+^| Internal
|
a|
[#set-var-types]
* Everything apart from Public API points are consider internal
* All Internal is consider non-breaking
* Any changes in this section is always consider non-breaking

2+^| Configuration
a|
[#set-var-types]
* Changing default value of all configurations and changing default behaviour.
* Removing configuration
* Rename configuration.
a|
[#set-var-types]
* Java:
** All new configurations will be turn off by default.
** Changing default value of all configurations and WITHOUT changing default behaviour.
* Javascript:
** All new configurations will be turn off by default.

2+^| Dependencies
a|
[#set-var-types]
* Javascript:
** Change of TypeScript version
** Change of React version (currently fixed version, but might be a range soon)
** Change of any peer dependency (range)

* Java:
** Change of Spring major releases (include all Spring related libraries)
** Change of any third party major libraries.

a|
[#set-var-types]
* Update of internal dependencies with minor, patches versions.
* Update of internal dependencies with major to make UAA works with latest Keycloak version.
|===

