////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License – EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
= User Authentication and Authorization
{version}, {date}, UAA Team
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: github
:toc: left
:toclevels: 4
:sectlinks:
:source-highlighter: coderay
:sectnums:
:sectnumlevels: 3

include::security.adoc[]
include::authorization/authorization.adoc[]
include::authentication/backend.adoc[]
include::user/principal-extension.adoc[]
include::rest-client/rest-client.adoc[]
include::javascript-client/index.adoc[]
include::javascript-a12-client/index.adoc[]
include::keycloak.adoc[]
include::gdpr.adoc[]
include::breaking.adoc[]

[[runtime-configuration]]
== Runtime Configuration

In a project using UAA there are multiple ways to run the application and pass the configuration to UAA.
Main configuration place should be the `application.properies` or `application.yml` file.
This method overrides the default configuration provided by individual modules.
For more detailed information see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[Spring documentation].
The default configuration is stored in `uaa-authentication.properties` and `uaa-authorization.properties`.
It's possible to create those files in a project, but in this case it overrides the default configuration provided by the modules.

[[runtime-configuration-mvn]]
=== Gradle

An application can be run by gradle spring boot plugin.
It's possible to pass the parameter from command line.

[source,shell]
----
./gradlew bootRun --args='--spring.profiles.active=$PROFILES'
----

[[runtime-configuration-eclipse]]
=== Eclipse plugin

An application can be run inside the Eclipse IDE via STS plugin.
In this case just add configuration options to `VM arguments`

[source,shell]
----
-Dmgmtp.a12.uaa.authentication.jwt.secret=[your_secret_key]
---- 

include::code_documentation.adoc[]

include::uaa_training.adoc[]

include::infrastructure_dependencies.adoc[]

include::migration/index.adoc[]
