////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License – EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
== Infrastructure Dependencies


UAA supports multiple authentication types.

- For LOCAL and LDAP authentication, UAA does not require additional identity providers.
- For OIDC or SAML authentication, UAA relies on an external Identity Provider (such as Keycloak or another compliant IDP).

In the table below, the infrastructure dependencies required by UAA are listed with their purpose, supported versions, resource recommendations, and configuration links.

[%autowidth.stretch,options="header"]
|================================================================================
|Dependency |Purpose |Supported Versions |Configuration Reference |Minimum Resource Recommendation |Notes

|Keycloak / Other IDP (only for OIDC/SAML)| Provides identity federation and single sign-on for OIDC or SAML login flows. | Keycloak 24.x, 25.x, 26.x. Other OIDC/SAML-compliant IDPs | Please use the links for connection: link:#saml[SAML configuration] - link:#oauth2[OIDC configuration], and use the following link for
link:#keycloak-setup[Keycloak Setup]. |None |Only required if customer projects configure OIDC or SAML authentication.

|================================================================================
