plugins {
    id 'java-library'
}

tasks.withType(JavaCompile) {
    options.encoding 'UTF-8'
    options.compilerArgs.add("-parameters")
}

tasks.withType(Test) {
    useJUnitPlatform()
}

dependencies {
	api project(':uaa-authentication-principal-extension')
	api project(':uaa-authentication-spring-boot-autoconfigure')

	api libs.springBootAutoconfigure
	annotationProcessor libs.springBootConfigProcessor
	api libs.springBootStarterValidation
}

description = 'UAA:: Authentication:: Principal Extension:: Spring Boot AutoConfiguration'

