/*
 * SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
 *
 * Copyright (c) 2012-2026 mgm technology partners GmbH
 *
 * Dual License
 * ------------
 * This source file is part of the mgm A12 Platform and available under
 * a choice of two different licenses:
 *
 * 1. Open-Source License – EUPL v1.2
 *    You may redistribute and/or modify this file under the terms of the
 *    European Union Public License, version 1.2 - see https://eupl.eu/.
 *
 * 2. Commercial License
 *    Alternatively, you may obtain a commercial license from
 *    mgm technology partners GmbH, that permits use of this software
 *    under different terms (including support and maintenance services).
 *
 *    Please contact a12-license@mgm-tp.com for more information.
 *
 * You must select and comply with exactly one of the above license options.
 *
 * Warranty Disclaimer (applies to either option)
 * ----------------------------------------------
 * THIS SOFTWARE IS PROVIDED “AS IS” AND WITHOUT WARRANTY OF ANY KIND,
 * WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
 * LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
 */
package com.mgmtp.a12.uaa.authentication.saml.internal;

import java.util.List;
import java.util.Optional;

import org.opensaml.core.config.ConfigurationService;
import org.opensaml.core.xml.config.XMLObjectProviderRegistry;
import org.opensaml.saml.saml2.core.AuthnContextClassRef;
import org.opensaml.saml.saml2.core.AuthnContextDeclRef;
import org.opensaml.saml.saml2.core.RequestedAuthnContext;
import org.opensaml.saml.saml2.core.impl.AuthnContextClassRefBuilder;
import org.opensaml.saml.saml2.core.impl.AuthnContextDeclRefBuilder;
import org.opensaml.saml.saml2.core.impl.RequestedAuthnContextBuilder;

import com.mgmtp.a12.uaa.authentication.saml.RequestContextDataGenerator;

/**
 * Converts Extension objects generated by implementor into SAML types for AuthnRequest.
 *
 */
class AuthContextDataConverter {

	private RequestedAuthnContextBuilder requestedAuthnContextBuilder;
	private AuthnContextClassRefBuilder authnContextClassRefBuilder;
	private AuthnContextDeclRefBuilder authnContextDeclRefBuilder;

	public AuthContextDataConverter() {
		XMLObjectProviderRegistry registry = ConfigurationService.get(XMLObjectProviderRegistry.class);
		requestedAuthnContextBuilder = (RequestedAuthnContextBuilder) registry.getBuilderFactory().getBuilder(RequestedAuthnContext.DEFAULT_ELEMENT_NAME);
		authnContextClassRefBuilder = (AuthnContextClassRefBuilder) registry.getBuilderFactory().getBuilder(AuthnContextClassRef.DEFAULT_ELEMENT_NAME);
		authnContextDeclRefBuilder = (AuthnContextDeclRefBuilder) registry.getBuilderFactory().getBuilder(AuthnContextDeclRef.DEFAULT_ELEMENT_NAME);
	}

	public RequestedAuthnContext buildRequestContext(RequestContextDataGenerator dataGenerator) {
		RequestedAuthnContext authContext = requestedAuthnContextBuilder.buildObject();
		authContext.setComparison(dataGenerator.comparisonLevel());
		Optional.ofNullable(dataGenerator.generateClassReferenceData())
			.ifPresent(classRefs -> convertClassRef(authContext, classRefs));
		Optional.ofNullable(dataGenerator.generateDeclarationReferenceData())
			.ifPresent(declarationRefs -> convertDeclRef(authContext, declarationRefs));
		return authContext;
	}

	private RequestedAuthnContext convertClassRef(RequestedAuthnContext authContext, List<String> classReferences) {
		classReferences.stream()
			.map(this::convertClassRef)
			.forEach(authContext.getAuthnContextClassRefs()::add);

		return authContext;
	}

	private RequestedAuthnContext convertDeclRef(RequestedAuthnContext authContext, List<String> declarationReferences) {
		declarationReferences.stream()
			.map(this::convertDeclRef)
			.forEach(authContext.getAuthnContextDeclRefs()::add);

		return authContext;
	}

	private AuthnContextClassRef convertClassRef(String classReference) {
		AuthnContextClassRef buildObject = authnContextClassRefBuilder.buildObject();
		buildObject.setURI(classReference);
		return buildObject;
	}

	private AuthnContextDeclRef convertDeclRef(String declarationRef) {
		AuthnContextDeclRef buildObject = authnContextDeclRefBuilder.buildObject();
		buildObject.setURI(declarationRef);
		return buildObject;

	}

}
