/*
 * SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
 *
 * Copyright (c) 2012-2026 mgm technology partners GmbH
 *
 * Dual License
 * ------------
 * This source file is part of the mgm A12 Platform and available under
 * a choice of two different licenses:
 *
 * 1. Open-Source License – EUPL v1.2
 *    You may redistribute and/or modify this file under the terms of the
 *    European Union Public License, version 1.2 - see https://eupl.eu/.
 *
 * 2. Commercial License
 *    Alternatively, you may obtain a commercial license from
 *    mgm technology partners GmbH, that permits use of this software
 *    under different terms (including support and maintenance services).
 *
 *    Please contact a12-license@mgm-tp.com for more information.
 *
 * You must select and comply with exactly one of the above license options.
 *
 * Warranty Disclaimer (applies to either option)
 * ----------------------------------------------
 * THIS SOFTWARE IS PROVIDED “AS IS” AND WITHOUT WARRANTY OF ANY KIND,
 * WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
 * LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
 */
package com.mgmtp.a12.uaa.authentication.saml.internal;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import javax.xml.namespace.QName;

import org.opensaml.core.config.ConfigurationService;
import org.opensaml.core.xml.config.XMLObjectProviderRegistry;
import org.opensaml.core.xml.schema.XSAny;
import org.opensaml.core.xml.schema.impl.XSAnyBuilder;
import org.opensaml.saml.saml2.core.Extensions;
import org.opensaml.saml.saml2.core.impl.ExtensionsBuilder;

import com.mgmtp.a12.uaa.authentication.saml.RequestExtension;

/**
 * Converts Extension bjects generated by implementor into SAML types for AuthnRequest.
 *
 */
class ExtensionDataConverter {

	private ExtensionsBuilder extensionsBuilder;
	private XSAnyBuilder xsAnyBuilder;

	public ExtensionDataConverter() {
		XMLObjectProviderRegistry registry = ConfigurationService.get(XMLObjectProviderRegistry.class);
		extensionsBuilder = (ExtensionsBuilder) registry.getBuilderFactory().getBuilder(Extensions.DEFAULT_ELEMENT_NAME);
		xsAnyBuilder = (XSAnyBuilder) registry.getBuilderFactory().getBuilder(XSAny.TYPE_NAME);
	}

	public Extensions buildExtensions(List<RequestExtension> extensions) {
		return Optional.ofNullable(extensions)
			.map(this::convert)
			.orElse(null);

	}

	private Extensions convert(List<RequestExtension> extensions) {
		Extensions samlExtensions = extensionsBuilder.buildObject();
		List<XSAny> extensionsData = extensions.stream()
			.map(this::buildObjectTree)
			.collect(Collectors.toList());
		samlExtensions.getUnknownXMLObjects().addAll(extensionsData);
		return samlExtensions;
	}

	private XSAny convertObject(RequestExtension extension) {
		QName qname = new QName(extension.getNamespace(), extension.getName(), extension.getPrefix());
		XSAny extensionData = xsAnyBuilder.buildObject(qname);
		extensionData.setTextContent(extension.getValue());
		extension.getAttributes().stream()
			.forEach(attribute -> {
				extensionData.getUnknownAttributes().put(new QName(attribute.getNamespace(), attribute.getName(), attribute.getPrefix()), attribute.getValue());
			});
		return extensionData;
	}

	private XSAny buildObjectTree(RequestExtension extension) {
		XSAny samlExtensionData = convertObject(extension);
		extension.getChildrens().stream()
			.forEach(child -> {
				XSAny childObject = buildObjectTree(child);
				samlExtensionData.getUnknownXMLObjects().add(childObject);
			});
		return samlExtensionData;
	}

}
