////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License – EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
:source-language: javascript
==== Localization

===== Login Page

The localization will be done by the external side.
The UAA will get one Localizer from @com.mgmtp.a12.utils/utils-localization as _localizer_ props or by _useContext_

===== Example

. Create locale resource
[source,javascript]
export const localeJsonResource: LocalizationTreeMap = {
  de_DE: {
    label: "Sprache",
    auth: {
      form: {
        title: "Anmelden",
        username: {
          label: "Benutzername",
          error: "Geben Sie bitte den Benutzernamen an"
        },
        password: {
          label: "Passwort",
          error: "Geben Sie bitte das Passwort an",
          reset: {
            label: "Passwort vergessen"
          }
        },
        submit: {
          label: "Anmelden"
        }
      },
      error: {
        authenticationfailed: "Authentifizierung ist fehlgeschlagen! Evtl. falsche Benutzer und/oder Passwort-Eingabe?",
        logoutfailed: "Abmeldung fehlgeschlagen!"
      }
    }
  },
  en_US: {
    label: "Language",
    auth: {
      form: {
        title: "Login",
        username: {
          label: "Username",
          error: "Username is required"
        },
        password: {
          label: "Password",
          error: "Password is required",
          reset: {
            label: "Password forgotten"
          }
        },
        submit: {
          label: "Login"
        }
      },
      error: {
        authenticationfailed: "Authentication failed! Maybe wrong username password combination?",
        logoutfailed: "Logout failed"
      }
    }
  }
};

. Create localizer
[source,javascript]
const localizer = defaultLocalizerFactory({
    locale: Locale.fromString("de_DE"),
    translationSource: defaultTranslationFinderFactory(
        createTextResolverForTreeMap(localeJsonResource)
    )
});

. Passing localizer as props or wrap localizer by LocalizerContext Provider

[source,javascript]
<LocalizerContext.Provider value={{ localizer ...otherProps }}>
    <LoginPage ...props />
</LocalizerContext.Provider>

[source,javascript]
<LoginPage localizer={localizer} ... otherProps></LoginPage>;
