////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License – EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
:source-language: javascript
==== Automatically renew tokens

===== For not OIDC authentication

Token renewal is started by default.

[source,javascript]
----
import { TokenManagement } from "@com.mgmtp.a12.uaa/uaa-authentication-client";

TokenManagement.getInstance().startService();
TokenManagement.getInstance().stopService();
----

===== For OIDC authentication

====== Using hidden iframe

** Create your own html and reference to UAA silent_renew.js file.
** `silent_renew.js` can be found from "node_modules", "@com.mgmtp.a12", "uaa-authentication-client", "resources", "silent_renew.js"
** Due to security reason, the `silent_renew.js` file need to be reference in your `silent_renew.html` entry file.

It's completely dependent on project to set this up.
Here is example:

====
* Serve additional html file eg: silent_renew.html with content:

[source,html,title="Example:"]
    <!DOCTYPE html>
    <html><head>
        <script type="text/javascript" src="[your path to silent_renew.js]"></script>
        </body>
    </head>
    <body>
    <div></div>
    </body>
    </html>

* Configure your webpack to serve it as separate resource:

[source,javascript,title="Example:"]
new HtmlWebpackPlugin({
    minify: true,
    filename: "silent_renew.html",
    template: [directory_to_your_silent_renew.html]
}),
entry: {
    silent_renew: [your path to silent_renew.js]
}
====

[[using-oidc-refresh-token]]
====== Using refresh token

When `enableRefreshTokenGrant` is set to true, the UAA library renews access tokens via the OAuth 2.0 refresh_token grant.
This replaces the default silent-renew mechanism that uses a hidden iframe

*IDP Configuration Requirements*

* One-time revoke refresh token.

* Refresh Token Rotation

* Short time Refresh Token lifetime - for example, 5 minutes.

For Keycloak settings: <<keycloak-revoke-refresh-token, Keycloak Revoke Refresh Token>>

[WARNING]
====
All security configurations from IDP must be applied otherwise the application will be exposed to potential security risks
====
