////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License – EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
==== Service Worker for token injection

UAA provide a Service Worker to inject token for each request you register. Have 2 facilities: `register` and `unregister`

- `Register`: register(urls: string[])

- `Unregister`: unregister()

===== Configure your webpack to serve uaa-service-worker.js file
There are serveral ways how to register UAA javascript file to your application.
Below is an example registering uaa-service-worker.js via webpack.
Feel free to adapt with your project.

[source,javascript]
----
const serviceWorker: webpack.Configuration = {
	mode: "development",
	devtool: "eval-source-map",
	entry: {
            service_worker: Path.resolve(
                __dirname,
                "node_modules",
                "@com.mgmtp.a12.uaa",
                "uaa-authentication-client",
                "resources",
                "uaa-service-worker.js"
            )
	},
	plugins: [
            new HtmlWebpackPlugin({
                inject: "head",
                filename: 'index.html',
                template: "public/index.html"
            }),

	]
}
----

===== Importing:

[source,javascript]
----
import {  UAAServiceWorker } from "@com.mgmtp.a12.uaa/uaa-authentication-client";
----

===== Register:

Example: You want to inject token in request have url "http://localhost:8080/image"

[source,javascript]
----
const urls: string[] = ["http://localhost:8080/image"];

UAAServiceWorker.register(urls);
----

===== Unregister

[source,javascript]
----
UAAServiceWorker.unregister();
----



