server.port=9092
mgmtp.a12.uaa.authentication.types=OAUTH2,OAUTH2_CLIENT

spring.security.oauth2.client.registration.uaa-auth-client.client-id=uaa-ssr-client
spring.security.oauth2.client.registration.uaa-auth-client.client-secret=ac295f8b-5b88-44ef-81cf-506e83a3bfde
spring.security.oauth2.client.registration.uaa-auth-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.uaa-auth-client.client-name=uaa-ssr-client
spring.security.oauth2.client.registration.uaa-auth-client.scope=openid

spring.security.oauth2.client.provider.uaa-auth-client.issuer-uri=${config.idp.url:http://localhost:9090}/realms/UAARealm
spring.security.oauth2.client.provider.uaa-auth-client.jwk-set-uri=${config.idp.url:http://localhost:9090}/realms/UAARealm/protocol/openid-connect/certs

spring.security.oauth2.resourceserver.jwt.issuer-uri=${config.idp.url:http://localhost:9090}/realms/UAARealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${config.idp.url:http://localhost:9090}/realms/UAARealm/protocol/openid-connect/certs


mgmtp.a12.uaa.authentication.oauth2.idp-logout.enabled=true
mgmtp.a12.uaa.authentication.oauth2.post-logout.url=${config.ssr.url:http://localhost:9092/}

mgmtp.a12.uaa.example.dev.app.url=${config.server.url:http://localhost:8080}/loadAllCompanies
